### ISSUE TITLE
effect teardown only called at unmount, instead of every time effect deps change

### ISSUE THREAD

**Issue by fuzetsu** [ArthurClemens/mithril-hooks#1]
React hooks will call the teardown function each time the effect is restarted to perform any necessary cleanup. Mithril hooks does not do this atm. 

[Example flems](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYgAvhmr1GSFgCtyPPgKHTeVMOwAEwDQHdC7VgAkYMANZgMGgK5gSAZXY0BlmyQCi+fCQiaRGgLwadPqsUMTGZmAAOlQxquoaAIIADskBuiER5gAU2QCUAQB8WjEaGvGaKABuNHCWtuwAarXY6a4OTiTZAOSsJAgwujBQcAAm3Xml1rYeXj65Bf7FwFNlFRqsNFSjpFDp+UUaydk1cJNUZWV62zA6zDSjo25VguwAMoTqgiRQPRBwhAgpm6lk221250uGigJHYVigFwOSwyNzuMLoMBez1eHy+VB+fwBQJBGy2Ox+kI0Yg01RalJhcIRQR6dBohCoJJQq2Z3XZySs7BJ2lOVhISA0p0sfD5AvFJEODWacGyJGYjigAHNYcwRSQCiJKdhzgaYjE6MwMVZ+NlRjAIFYGPxmAAjGCjACelhSyXOIDwtlIPkIfHI0gAjGgkABWACconEIFoDCYzAgYHkIFUSnYwhEuBAAKo5goEmT0mCBjC3BA8MQ0g47GSYCQAHoW1bkqYNamYHQWxXQsQAAIAJmYaGYABZ+yEqxb2cw5H6QOx3ckpOBoIRkjmxKWNwOqwBaVgmYt4WtMBtN1vtqid7u8PuH4gns9gIcTqPMKMt0afdgZ0rV9T0iRcM1XdcmEgMId1EfMkw3ZIYRoHw30iI91BoKABCgUQgA)

As you change the values in the input new event listeners are added, but never removed (until component unmounts).

**Comment by ArthurClemens** [comment]
Confirmed. Working on a fix.

**Comment by ArthurClemens** [comment]
React documentation says: "React also cleans up effects from the previous render before running the effects next time."

I understand this as (from the library POV): call the cleanup function just before running useEffect. @fuzetsu Your code example would run exactly the same as it does now, wouldn't it?

**Comment by fuzetsu** [comment]
@ArthurClemens You're right that you call the cleanup before running useEffect, but the cleanup called is from the last run of the effect. So the `window.removeEventListener` from my cleanup would prevent a buildup of listeners.

[Here is an example using preact hooks with the same code.](https://flems.io/#0=N4IgzgxgTg9gNnEAuA2gBgDRoLoZAMwEs4BTMZFUAOwEMBbE5EAOgAsAXOxPCGK9kvyYgAvhmr1GSFgCtyPPgKHTeVMOwAEwDQFcwJAMrsaAjLv0BRfPhIRNIjQF4NABygkadgBIwYAazAAHSpVdQ06J3DCaBhWAAo3Dzs2AEpg4NDNAEEXF0i4lKcAPi1gjQ1MjRQANxo4M312ADU67Ei9Q2MBOIByVhIEGA0AdxgoOAATHrSqco6rGzs4guLS2fKKvjDWGioJ0ih8wscSlzjauBmNkcI9mGHmGgmJi2rBdgAZQnVBEiheiBwaJ+HpmHZ7A5XDbudg6KCzFYnG53B7uOgwN6vd5fH5UP4AoEQEFg3b7P5QsRVC7YKEwuGzOi9Og0W6gqplDaMnq3Fw6dhs7QXHQkJAaC5mPg8vmikirRotOBxEjMYxQADmJHYzCFJEKIihNOCInSVGCiU8Wvce3xjJyLhSZgmMAgOgY-GYACMYBMAJ4pEB4fSkOyELZMACMAGYkOHROIQLQGExmBAwPIQKolOxhCJcCAgVQAhQJEnpObkq6Jsw5AGQHDENIOOwXGAkAB6Ns6KguPxqlMwOht8vsAAC4bQzAnaAAtFAIMxw22Jt92EP3BbmJXq+n2D6XFJwNBCC5s2ISwfWL4Apu6FWa3h60wmy3253u73+4Ph2Op5PZ-PF0vfwwCXFc2yA68t3vEBd33JhICgY9T3jRMDzoaJYFYWtH0bdhm1bDsux7PteEHdCYlYEdfwAJlA9Q23IzDmDIABWZh0Kobda1gg8EKQ0Q81Qph0PYVhELgacIPIEQgA).

You've probably already got a solution, but last night when I reported I made a quick attempt at a fix. The teardowns were being stored in that map using `fn` as a key, but that won't work because `fn` has a new ref each redraw usually. So I changed it so that the teardown was keyed by `state.depIndex` since that should be consistent for the given effect, then when `shouldRecompute` was true I'd call the cleanup at that `state.depIndex` before pushing onto the `state.updates` array. 

[Looked like this](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIC2BLeALATllALS4D2ZA1mAHQBWYIANOLPmVFGgNoAMTvALosAZkQiNU3UADsAhhghoQNXPAxcWsMjMS7lIAL5NZCpemx5CJclVoNmIbboj70MeAAJYAV3z5XeABleDlEAG4AHRlo5zAvWDlOTwBeTwAxHxkELB0aAAd2eDJ4AE98iBpEzhoAIywZJAAKaM8MrJy8wpKS8srqqGiASiiY7J14zzBYXGQfGAAlVyQIfFTPJqHUgD5WzwB6fc8AYSSoTwxPAHccXAbPPAhPEQ74XJlPWrIkUqmyT1cADcsOwZIpdGBrrdPHJPABzKBkWpJTwNeJybJPMgiC4bKBYShPEQwDC0XJbJA6ADkCTIGHyUDkDT2GBoASQ+DkV02o1iEy8PnySDCEAAIhB8pC0itJTtPMA9nEvOjEOtfP5AiERaM2krUY0IAAPdYqyoysAASQNhoA1Dadd5+Z5ChBAeLZWlTTRzVrEGBuA0VobBJ4AD6hzzcQQOvVgcjzJBLbT0nyq6USqUpNJZFZiGTIPZtAD8D3wPieh08AEEoFc5KVIcn8qmIIXPKhq-56zQsGAq13Sk1zUM28XPOaaDAZHC8J5tp5eKO2p4SwBCCeu1aDpqGphYLYpefGrNpF1ujMBwRbSsAeRkUF+TZb11mHx0WJxj3HGc8uDkjb-acCw+ZdQI7VcvUgeBBQOI4AFF6TKGEBw7HQH0dFNVTCC4yCyeAlw7EQkkgcJYM8K1ASSLAkE8SioHLJhx3+GQSjuac9i9H1Qj9ANrRDdNJQdAJoPwD441wqBEzgOlmwiaJDF5cYZEmCARBEOAvDSJpeyrMBSmydYiKgSAD3nJoRBkRjhzlBUQNjbinjSdUAl0X0IBjJ1xITJMZOfbMhRFd0wCHDMRj2LAcSaLzJJ8zCIC2WzQL1MsZFOThkVgSh0g+LTTPlJc9UQOR8EpK4cueGQeSXSsq28M4MsoC5608YS-A+WEXmyN48nInEMVKRi5CQGicAef4vyKkqyDKsBUCXCKNjKCpsQeCBitKnKs08SIQE6zoYhABKlzaSsQjIAIHjuSE8F7Z5XneMbPieAZkBhAUwVw3RjqmByaEmjbaCgqLfplK0g0Y-7ppkMKQNAk6jird6ME++BGIGFqIGIFyVjWbCYH-LwdFgVtYbhr1IZmmggZ2gB9HbGOmWYkHmCAlgNfAYbhzxDDbBS20KtaprKk1fop5SaDhCB4GBkVvQlMGjRHUmIqaMWjtJtoxc2JdycFgG5Y8CAZcQOX8gVw0ldAnnSa9QVhT9AofDjFoNdRPs9Oyb6S02OV8yuTwAAV2GwSAmgCMAOEBRz5wCABHct4irGQsAwMJ3nSTlFDDiRI-ioY-tfMOsjSqAGuyy2ufbFri-quRMuyttOe5+TFL1O2RTc9ZtOTt4kgANSSBjPD9gf6IgbL1jo8s5Sn+KbMVTyHLVPwXOCByPOUrxAyNEXZdNS1rTtB0FqaCDfqgwV1dAyCHP9bfg3WBocCwfvB-cvZrbaVrRMjNsb5FO+fEmBtlnvPV2eozy5CdqPaenpz6314kGaMBUnQjzfusNBY9spNFnoxe+Tdr7wIAYgo0-Fh4QCuDA9+rsT4ACkgg3gAHJU3gIQacEVByYPLFsVcW16FMJYWwuEHCmiQNwmAKhQwr6V0ZnMRYyxVg8jIiXBocIMYci5BceYbwGRPDeIoWangACytxrBQmSByMg+QASGlYRiCA4j1Gcn9gMMADN-gVHwCIc6qdMRTHjJJYeJQnowg+L2MA5Ylyf2XMYNs989jIJkHzMYRp8jnVpJvTwTsICdzSE-XuUAqFgN1IvEUy8NSuXXgvTJXDx7lRwW-PB1pTJtiWg4nEoCTzbV2vdHQO0lwllnsbSo+8SHBgrmBWib8hJSzalkgKiA3Ld2fq-MejFanl1GMk6IqT0mOkydkuCakNLrFUupBAqsyzxVGLs-AGTJjZIADL1lwvAI55zNIAmORcmGOzDRpLufsh5kAljM2JmsLS7IfDgqaSsqA-Y4SwvgOXYpQLlRLycivTUVSQKVgznSS6Twlh1y8JSWAhiACauE6rtWMv8Nga1VRfnyS-c4ppPCMgAF5EFKDQTwAAVf4lJLq9kYqUaliQPj5H-JCDE+pRp7W6u1a6swRUlWQnCHw4J4B8v5aqllKJ2U3GSLUJ4UFHr5OWQUhF+dqmTANYU9BaQz571mdYgAZO6+VyKxigRLPk7BDqbVtg7EG-AcJFIlMyZLeAVDRS9mlfAGYXc8qJWXHqbguCphSyoU0pB6x26LIcla1lkiHRRsmEgBNYRk1pBJQ9Q8+VwFOjEdAp1P094IPvokrm38xI5rfk0MijCjTopFHNV2X85jgtEQEYE4jc0wn2hM5cBDubloxiJD4mbGnjmrUm3APb117D2H2+EA6x7xrAImmYVUkkOj+QC+5AoQWqUfj3UtTr5xppqhjHEt1YSeLAL2RANEkR0BOXgbCxrzgsS8Ka+Z9tkDuNRF4P8kIWLZvgIgfAdqvA7rHmQwtOTi3AG8Fi3QoaP2rOnoYJuZ7Z5bIffmf5ey26QCMRAZGXcLJWVCqi+yZTMUVLXtqPD-iJJSSfGmRDgUMwhUlE3DNihkZYE5chrDnHVPqaQGQl1JsL75DbCWYjSyLKbBXR2Uzxam4n0gm6zwnqJPeWknFaRbQoJabIGp5A5lKpSIdNEs9KnvM6aYyeljT60VZMgCXBqPHLLfkUzsPY2SvNNB9o23jSWwBrsfWxp0Nw8AAAkKDUC7k2d8ugkWsqDlY3LYDxP5MnixFYqK2g3lqBBhANAZVYDhJVQErWRkOUYmm6+brCLEQgMA12+8OxRlm1zfe5sOz8CXFxABC3hAbYzKthcS24bEcMYtpcYtDF+2MXIaxlYADSEAJSljro1Fa52ARRw+FcV8hLZOqjrJCFKng0K-CJiTK2TdkltHE8Rlr3xo5NqSi2uduTyMibchu5y2KhO0WGywsTpNWG-HG8uIbcO8cm2OzQbx+A4J11wE0AYa7oltDzGcInS5OvdZ1X1gbODcemjG99QzHZWEMW+sd7bh2ubmn2+tydHa-Sy6lzEtduoKOiZk2edHvMP7MYrV4bGqxYdtcbcTiByOMWo9Xtr0mmPKnY9Jyscn1DQKE4R3DM9lX8y6CaMT0CNAA8Orq5KZX-uA+O8qGEVhbjvoR9D+mu4kkXIdgj1URPHJXDx7oxu5ndUD0bDnn7oFHBKirHYPgJo1yyISHxLoYgVawByFqDAYgtengsWIHEEvOvSas84Oz8B6uUda5xVbXXEX9erXWlDY38OzdI9dCju3GuXfpqH5b1PpoN1u6L9wAPNBN+iz1lDWgs9gpDEEFT86tPb2M5z22Pv6Ei-L+Hxb-HY+QKQ7hqe2ZP9ic6HySoxwGVyJgCHHV+xmzbB0GIyswWUgNJmBAoQ7EN3wBAJkACGRijhF2PzKkO2SQUkcEgBgH2kkBAAABYABmVAAAVmIAoIAE5UAyCjATAQB5BFBlB6BGAtAdA9B4BlAU4osyMitcBSs7BGJsk3IJDIB3kTlDBnhg5PAqQaB9hLACAiBSAyt7AwAqRog+RMkqx8hrE0gRCxDqAMtU1xMCMGYL0iNIAlkqRZhOB-grhzpJIqQK5DlvlpZMtv1+YnRAIkAYAIUNg8p8gGkoAV0bhGhppetho4IPt4BHkQNXBFEqRYB8RMoqRGJAjgiV0z1fCoQYirg2QuMyAo4EjAhkj4hUiK90jMjKBsjfwMQgjVgK5jBIw6Irwf8t0LgmgqRU4GgmjuA2wMB+iGhZImiyNZ4U8khGIACZBZIOx4coJR5K8-pioY0D834tg6MEklY9ixhWRkY8IhwyBfBtU6hvgBpqwjClZCDoANJ3hSCABGag1AXgFg0wDg9AKoMAbgpwXgwIAwQwYQEAWvagHgb48wTAUxIgRwPwLgdANQeASUVAQ4LIfISgOEKoOkVQuEqAAAAQACYaBeAaAyD8SrAiAaBsAZAuDHA2llBphCB8h+DQSWB2CYSXQSVNC7BiB0Q7lVgjAgA)

**Comment by ArthurClemens** [comment]
Yes, this is basically the fix. I am adding a test before release.

**Comment by ArthurClemens** [comment]
Fixed in https://github.com/ArthurClemens/mithril-hooks/releases/tag/v0.5.6

**Comment by fuzetsu** [comment]
Thanks @ArthurClemens 💯
