### ISSUE TITLE
timing difference between react / mithril hooks

### ISSUE THREAD

**Issue by fuzetsu** [ArthurClemens/mithril-hooks#2]
I'm not sure if much can be done about this, and it might have more to do with how dom refs are handled than hooks themselves (`ref` vs `oncreate`), but I figured I'd file it to see what you think.

I have 3 example of a custom hook that I wrote, worked well in preact/react, but not when I tried converting to mithril. My current thought is that it has to do with a different in priority for `useState` updates during a redraw.. but I haven't dug too deep.

The issue is that after calling `setElem` from the `oncreate` lifecycle hook in mithril, the `useLayoutEffect` hook is not called quickly enough to allow me to animate the element.

[React](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgK5wYAZWIZGFOQoAyGAJ61ZxAKJgwMalNaSAvJIBKMDOYA6acVKzXJWCNQBOtQgAKe0difD8HRkNYHAYAShcXNw0YQ2FfTQcANxgAQTQILFUIek9AmQgCqRtiX1kYdXoRGF9GtFgMHMlWOOsAPmkXSUlk5DhCWgB3dQViRQnJgF1PeSUVRkDKiGIEtGHR8anKgHMZmDmFk+WbVeVVGE2q3f36CUlkGBizoxjrlLuNrshiltHoDMZTOZAoFelYBsBgcNYFIACYOFGeMAYKAKRGSCBgSSBQ6TE69BF7YZU2bzKaBWr1Z5U4YEolNdKSABknMknxgWF67MYvkCfIFeMsnwUg0pzIACv5vAp8L54LQoDlAvQOl1ubyYlyedrsg8xXE4vhiIQmNDYQM0RgMQAfJ2SGkLQJYnEwc0SvGq4iyXx7GH9IkOjE1Oo+4Hsd4kk7qMWLIGUgNBvbIPEkih4gAeYfdRzQx0CBasNjQsigUEkAH5JABCBMlySISR5uK52Vu87RfnAxYuViJVyvKS5AAOk7KdplLzQbzGC3UxFox2OsG+-awf1WaWFmU6eQKRWIJTQ5TxQpa7ZgYYpzOGMHwEh0sEtvgwi7AtF8HhsAByOBqGxB4AAY4kAvFn1fYh3xfWpvzgbYL08QCkJ-P8PAAVnA8CsDgaCe2GLJaAgDEX2oKAIBEAAJGAIGOEgYN5OCEM-ZDf3-dCQLAwIAEYoIlbtmWNY87wfViXzfD9MLgbiAMkYDQNgQJIOIp9JHTYNJDQGBJkkBVaCVB4USaMMX0dFFDByBhNAgCQmBaQIMK-RdUPZFFAPUcz9N9HsR0pHpgR0vYsECPFAKKSofLxCLAIAIwMNc0B86RJHoABhGjqAAa3bUM4UkNcNzU3o40AgAVddNxgQCu2zBZDS8VzCAE9KErgSdv3SmRVTAdtZh3GZ4NgdsZBRRzJygXR20AyoaP0gBaRKoFofLAO6bp1EA-JCnuSQAFl6vNUSqQSyd0sAgBJSRsEka1VTdWgSsIVR8SkRyRg6XxJEma09ite8xREfE4G0-laByFF8Aa4FdiClwQnMAARAB5I6VSYNERQiqdJy7SRzOoWRYjCRLaBRHRdkoEAFFgcwLwQHgACZEHAtgOBATAcDwcI4AEGh6EYZgeDYRYqCWvKWdQHmuDwbw-ACOmg3IHgSGISc4EQAB6XXZDQSc8uOcITN1pX-EIAABcD8Dt1ndamiQLZ8K38HgHD8G8NB8H4On4Mnbh6b8CBJ1EdhOD5nhVVCfBJ38FFZCZ+hvcqP2hbVvBNe1vWDaNk2zawXXY-Ma2BIANnwABOe2DawFES4ccx48T5Pz1Tn2M4DnQg7wEDfDDiPud54PS+IZbzKwVuqfbi8099-2qCzjXiC1nX9cN43TboYvx8nkzy6r2vwPrxv96nmek5T32u6XkBA+Dgeh4l1ggA)
[Preact](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYhWAK2olIAoZxHKYnAATAtAVzwBlTpkFF9eADKYAnhD2cAoqVKIw2sVoC8W7ACdETHcACQgIAGsYAB0oDW1Gby1GcjA-CHYACn9A9w4AShiYuItERxU-S0CAN0QAQShyRlNyaESM3XIG7R9OPz1Ec2hVRD9BqCRMGq0xPO8APh0YrS1imhh2CAB3czxOQw3NgF1Eg0RjU0QMzvJOAqhl1fWtzoBzHcQ9g9fjn1PzwSuXTuD2gmi0NEQSEY7ycUJ+JX+lzuSxK1jsDmcrncGQysy8C2AKOWSG0+EC+ESpEw8DwRK05FIWgyT02r1mhPuyy5u32WwyvX6wK5ywZTKG5S0ADJJVpIYhGLNxYI-Bk5Qq6Z5IXhFpzhQAFNLJPCsAJweA1DLQCZTaWyqFSmVW6qXNV5PKsTjsIQ4vELMmYCkAH0DWh5BwyVJpiDdGrpAU4ej891x8yZ-opPT60ZREnBLNe5jVh2RnPjifuNDpLKIdIAHqmw88oC8MvWvD4oHp4PAtAB+LQAQnzza0KC0tbyNd1oY+jihKMOMTEhVioO0tWw2Davp1INg2jWB3MnAgLxeSBhc-l8NOZWVlUmdQaTU4LSg7TpSpGY8QqY5wuWRBWE0GwkA9PxMFgUgID8BIfAAchgMBqUuAAGPJ4LpQDgM4UCgN6SCYBuN9EnggioJghIAFZUNQxgYEw6dliqCByApICwHgchVGCRByBeLgsNlHC8PAwjoNg0ikJQjIAEYMI1KdhSdR8fz-ISgJAsDyJgCS4K0RDkKQDJ0MYgCtDLJMtCgRBNi0A0ICNS58CGVMgIDfBHBqARLHITQhBGDIyIg2BiPFfB4PMFybJjadl05GYUUs+5GAyOl4KaTpIrpVL4IAIwcE8oEinQtGgTiUnCMcU3xLQTzPYzZlzeCABVT3PRB4MnKsDgdJIgvYWSStymBsEgkrdACUgx12K9oVDXCkDHXR8D87AsBsMd4M6LibIAWjy+AIDAcJ4OmaZzHg+pGguLQAFlOrdJSuVy7ASvggBJLQmC0L0AlDCA6vYUx6W0PyVgmPwtE2L17k9X81VUekYAs+UIBqfBWC6lE7nimJsiCTgTSEMkVVSjdsEnLQXLAPRmAEVg8ogfAbDuPg8CQdw32oNAACYUFQ8RJBABhmBEVgwBgRR+EEYQ0HEQ4SF2yJaCkMW0AJ3I6cxhQ+ETXg0C4ThcBQAB6U29CgbBwheCXHNNzXOAAAVk1DWDd1C9r8MBWFk03Vs0B2AkJ1htfkaXcOwGQkL8chsDUCQ1ZkDYIhgUPGB16X9ZEI2TfNy3rdtyBGCDnJndd933a9n2-ZTyJ-b8zhTbrtOw91khI+j1I44T4XRZkZJUnSPW-ANkBc5gM2Latm27ZLwe0nYJ2PdYXmG8Dhf0lYRAYCo1hkigcO+E7kQY57hWxCAA)
[Mithril](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgO4RihABK1aAazgVJAVzgwAysQyMtumABkMAT1rbiAUTBgY1Ka0kBeSVgWEATtAq6nAAOmhh4lJm9sJ+5jAYAG4wAIJoEFjGEPSekgAUMhDpUl7EftowWvQiMH5VaLBJMJKsAJSeAHzSYZKSkZLIcIS0slp6xPrDsgC6uWaGxjB5RQqtPX30EgNDI0UA5mMwE1P7s17zRozLxWtovf3IMLBYhw7PZzp6C1e362aWNjsjmcrjyeXaHi6wHWvVgUgAJgl4bkwBgoHoYZIIGB8jt5Gg9u1oXdeqTxpMRnkyhVbqTSdj8tVYpIAGQsyRPGBYdpMxh+PKc7mY9xPPTdEl0gAKfloPj0+D88FoUGSeXojWSrPZgq1knVCVVgtarXwiiYYIhXURGGRAB9bZJyVM8qj0TBjcLMYriNo-HdwZ18tbkaVyu71uxticCVpBdNfiTvb67shMXiKJiAB6Bp27Al5bMeLxobRQKCSAD8kgAhHj9pJEJJM60MxLHUd7M91tMwqwwhFNlIUgAHYe5eSKIIaC2B4n3QdRkZaYi0PZ7WCvTtcj7RWLxJppDJZegFTG82qN5qQ8V03owfASKywU1+DBoOBgWh+LC5ADkcGoNElgABlaX9MTvB9iCfe8yjfOAFGyO4vF-OD30-b9JAAVmA4CsDgcC216RJaAgZF72oKAIBEJQYAgPYSAgjkoJgl94Iwn8UIAoC8gARjA4VWzpfUmkvWcmPvR9nzQj8v04yR-0A2A8lAwjb0kJM-UkNAYFkSRpVlCA9DyeFqkDe8bXhexkgYcwjMYHT+VQ1930Qpl4V-LRTJ0j02z7Ek2nWTS7iwPJMV-TIik8zFQt-AAjOwVzQTzpD1NBKIgag1EbANrxXNdlPaSNfwAFVXdcYF-Fs0ymXVYsIXiUtiuBhzfFKZHoahFUWRtEhzDtnjyRJ8FM7kxmg2BGxkeEjOHKBrEbX8iionSAFo4qgWgst-FoWi0X9D0yRhJAAWUq40hNJWLhxS38AElJGwSRCFqZo4FoSRFGMLEpCMvpGj8OQXruM0OWeEQsTgDSuVoZJ4XwKr1luQLwjQLB8CwWwGBMrbtBwBh8Di2h4SsLQR2HW5KBAPRYFcJCEB4XjEGAtgOBATAcDwfBqDgAQaHoBzRB4NhpioFaNCQVB2a4PAfEUAJyCoX1yB4EhiGHOBEAAei17Q0GHNQ9m52Utbl-xoAAAQAJnwYD8AAFlN3wFYxop8H4KnoOHbhqa6iBh1EdhOE5ngzYV1bhmCKnlbwNWNe13X9cN42sCd+XoAj1QNAtu2sPwAA2LWZokNPzagTPgndvmvZ9gCAgDkXWCAA)

I managed to get it basically working for mithril, by calling the onenter function from the setter rather than waiting for the `useLayoutEffect` hook to fire again.

[Working mithril hooks version](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgO4RihABK1aAazgVJAVzgwAysQyMtumABkMAT1rbiAUTBgY1Ka0kBeSVgWEATtAq6nAAOmhh4lJm9sJ+5jAYAG4wAIJoEFjGEPSekgAUMhDpUl7EftowWvQiMH5VaLBJMJKsAJSeAHzSYZKSkZLIcIS0slp6xPrDsgC6uWaGxjB5RQqtPX30EgNDI0UA5mMwE1P7s17zRozLxWtovf3IMLBYhw7PZzp6C1e362aWNjsjmcrjyeXaHi6wHWvVgUgAJgl4bkwBgoHoYZIIGB8jt5Gg9u1oXdeqTxpMRnkyhVbqTSdj8tVYpIAGQsyRPGBYdpMxh+PKc7mY9xPPTdEl0gAKfloPj0+D88FoUGSeXojWSrPZgq1knVCVVgtarXwiiYYIhXURGGRAB9bZJyVM8qj0TBjcLMYriNo-HdwZ18tbkaVyu71uxticCdNfiTvb67shMXiKJiAB6Bp27Al5TMeLxobRQKCSAD8kgAhHj9pJEJJ0600xKOYHiXTeuN7M8BbSOwyBbrebUeWgavzwy3WOtpmFp+E0P0UgAHZe5eSKIIaC1t9YPVOSYi0PZ7WCvbtcj7RWLxJppDJZegFTHDvz15qQ8Udjn4CRWWCmn4GBoHAYC0H4WC5AA5HA1BoksAAMrRQZivQwL+xD-uhZTAXACjZHcXhQThIFgRBkgAKwIQhWBwChLa9IktAQMi6HUFAEAiEoMAQHsJCoT+f4ASRoHgZBRGwfBeQAIzIcKzZ0vqTTvruDGCZhwlAaRYnQZJsB5Eh9HfgmfqSGOsiSNKsoQHoeTwtUgboTa8L2MkDDmDZjBjvyxFaXhxAEUw8JQVo9ljh6U4Rn2Jl3FgeSYlBmRFCFmJxVBABGdhHmgIXSHqi4cdQaj1gGn5Hie+ntJGUEACrHqeMBQU2KZTFqAlxQJvRQYQ0kpWpvQdf1pIwcuwF9d+dIyPQ1CKos9aJFmRwXnFiT4PZ3JjBpMD1jI8I2cuUDWPWUFFBxY4ALTpVAtBFVBLQtApE1dfemSMJIACyjWdZIfZ0s1LZpcuuVQQAkpI2CSIQtTNHAtCHoQxhYlINl9I0fhyFDdxmhyzwiFicCSIqWC0Mk8L4E16y3G0YRhFg+DE9oDB2Td2g4Aw+DpbQ8JWFoK7LrclAgHosCuARCA8AATAALIgFHnRL0mIFLbAcCAmA4Hg+DUHAAg0PQXmiDwbDTFQZ0aEgqBq1weA+IoATkFQvrkDwJDEMucCIAA9J7jPLmoexa7Knu2-40AAAIS-gCH4FLwe+Pb9NFPg-CC5hy7cELM0QMuojsJwGs8CH9vncMwSC07eCu+7Xs+2gfsB3QWBx3b0Al6oGhh9HFH4AAbJ7e0SM3odQG3wTJ7racZ7BAQ58brBAA)

Feel free to close this if it seems out of scope/irrelevant.

**Comment by fuzetsu** [comment]
Reduced repro a bit further:
- [Mithril](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgO4RihABK1aAazgVJAVzgwAysQyMtumABkMAT1rbiAUTBgY1Ka0kBeSVgWEATtAq6nAAOmhh4lIYAA7RnnK+QRoAFMkAlJ4AfNJhkpKRkshwhLSyWnrE+iWyALrxZobGMMnEftowabn59BKFMLBY5TAOA3VeDUaM6V1mljZ2js6uqRke2cBdeRBgkskAhP0wWBl+w9p+4Wh5eYdY+BJWsPi00RjUClbxAAybkrf3xEeMHwrQwaDgCgg9HiAHIAKxwGG-AButAgABM-gN8NQoBAREoYBAAOYkX7-B5PF5vD7xACMXXYfVGnSuklOxHOVywyV+MJhFF+PJhACM7MR6ALpJJ6LiINQ1IhdqtshUqqV9sVShkmTCACq0YnE2AwtKCtl5LWySQAMht3mSMMIdKlMllpyaSuRWUkFXsA2SyPw6Nox0kusJUCgtEkAHVaH4oOjTV1WaxWWE7lhbAxkiHqNocAx8CLaOirFoYtFWZQQHpYK4oeC8AAmL6IL5sDggTA4PA4uACGj0RjMHhsGpUPFoDRIVA9rh4HyKALkKjncg8EjEaJwRAAen32jQ0TUxJxof3y-80AAAi38F98AAWK++Vf4HxofD8WuA6LcHW1ABNEojsJwfY8Neq4ALQlMEtYbng267geR4nmeF5YG+K7QHBqgaLeT5wvgABs+7ohAEg4TeUD4cEP5Dv+gFwMBECgROrBAA)
- [preact](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgK5wYAZWIZGFOQoAyGAJ61ZxAKJgwMalNaSAvJIAOAJxgZzACVq0A1nAA6acVKxrSSwIantaQgAKBydzIgBKX19-SQxbWyDI+OsAPmlfSUkU5DhCWgB3dQViRTLygF0g+SUVRkjie1kYRLRC4phYLCqYI0HGm2blVRgsgo0YbT0DY1NzSKzc-N7CyQgwSUiAQgGYLGzHYll7NDnCk6x8CR1YfFpbZwhiHSCABlvJe6PL4vDoYNBwT4QehBADkACY4DD-gA3WgQAAmAMG+GoUAgIhcMAgAHMSP9AU8Xm8Pl8ggBGObsSTIe71HqFC5XXpYSL-GEwij-HkwgBGBmI9AF0kk9FxoQ8iAO2SseWqtQqR1KFWyTJhABVaMTibAYfFBdtClrypIAGQ24KRGGEOlSmSOMCK6qGQaSXWEqBQWiSADqtHsUHRprmPVYSTQMWcxHwjjQ6Jg9kiPLStjNknRtGoshwDHwIto6J0PUoIAUsHMUPBeAAHIg4QA2NgcECYHB4HFwAQ0eiMZg8Nj1Kh4tBeJCobtcPAJuJF9H4fjVq7kHgkYi2OCIAD0B9k8Y8xJxtCwB6XxAAAnSfvhHz8ALT2aj4OkH9EQCTXxyJvgK5roOXy2NwNZhBAtiiOwnC9tu7heEBWCruuVCbngO57oex6nuedBXje97Pk+b4fl+ZSeHA36-sQB5UchwHoSAYEQXAUEwZ28EQSEYQRBu4ZYcQu77keJ62GeF5Xnx4SELepFwrRf6yRE+DwAArPgIRoCB1ZsXgHH2NBsH1KwQA)

**Comment by ArthurClemens** [comment]
It looks like the implementation of `useLayoutEffect` is wrong.

**Comment by fuzetsu** [comment]
Yes, could be a problem with `useLayoutEffect` 🤔  but it does seem to be called synchronously called during the onupdate loop which seems correct, and even on the oncreate loop. 

I'm wondering if the culprit is that the ref isn't set soon enough. In the other libraries I think that the dom ref is set before the update loop happens, rather than after. In mithril-hooks when `setElem` is called we're inside the `oncreate` event, then call `setElem` which uses `useState` which just calls `m.redraw` so it makes sense that I wouldn't be able to animate from in there. 
Only way I can think of this working would be if somehow `setElem` fired a redraw almost within the same tick as `oncreate` firing...

**Comment by ArthurClemens** [comment]
Mithril's `oncreate` is called at the end of the render loop. And `useLayoutEffect` runs after that. I don't see a solution here without a change on Mithril's side.

As a workaround I suggest to set the element styles in the oncreate function (or in CSS for cross library code): [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgkgO4RihABK1aAazgVJAVzgwAysQyMtumABkMAT1rbiAUTBgY1Ka0kBeSVgWEATtAq6nAAOmhh4lIYAA7RnnK+QRoAFMkAlJ4AfNJhkpKRkshwhLSyWnrE+iWyALrxZobGMMnEftowabn59BKFMLBY5TAOA3VeDUaM6V1mljZ2js6uqRke2cBdeRBgkskAhP0wWBl+w9p+4Wh5eQD0N5KHWPgSVrD4tNEY1ApW8QAMm0kdweA2exFeMHwrQwaDgCgg9HiAHIAExwJGA4EAN1oEAAJiCjvhqFAICIlDAIABzEiAx5giHvT7fcHxACMXXYfVGnSuklOxHOVywyUBSLxECxSIogOQgLyIqRACM7MR6NLpJJ6CSINQ1IhdqtshUqqV9sVShkuUiACq0KlU2BItIyvnXSQW2SSABk3u8ySRhDZGo2bvdWrQ1FOTQNWKyOTD4ckWPweNoTxebw+Xx+-wA3PLwym0xnwW9obD4YivCEQABWUIgAuJ8MVewDZLF9NpZtJvLsQt5einLC0LEwA3peNtjtobRQKC8pPWikL2iSADqtD8UDxzsBNS6vNYvLCT1H2gYyTT1G0OAY+CVtDxVi0MWivMoNHT0WgMD8eBKhgSr9F+eiwK4CKwngACciAojBbAcCAmA4HgxJwAI37CMwPBsDUVCkmgGhIKgKFcHgPiKAE5BUOc5A8CQxDRHAiB3Je0RqFSxLpjcVH+NAAACKL4H8+AACx8b4NH4D4aD4PwX7gtE3AgHAUYQNEojsJwaE8PxNEALQlMEX70XgTEsWxNwcVxPFYFJ1HQMZqgaIJYl1vgABsNwShIjkCVALnBApWHKap6kBFp+GsEAA)

**Comment by fuzetsu** [comment]
Agreed. I'm not sure if this is possible without a mithril change...  I guess this should be closed.

BTW, any concerns about this difference in `ref` and `oncreate` between React/Mithril for `cyano`? I guess just something to be conscious of when writing components.

**Comment by ArthurClemens** [comment]
Good point. I will add a note to the documentation.
