### ISSUE TITLE
Storybook Infinite Loop on useEffect

### ISSUE THREAD

**Issue by davidroman0O** [ArthurClemens/mithril-hooks#3]
Hi!

First of all, this library is an excellent idea and I love it so far.

I found an issue on Storybook that could be a another good idea to fix. 

I looked at your code but I didn't found where it failed 😄 

With a simple ["Storybook for Mithril"](https://storybook.js.org/docs/guides/guide-mithril/) and a simple story and component, it failed.

File `stories/hooks.stories.js`

```javascript
import m from 'mithril';

import {
	storiesOf
} from '@storybook/mithril';

import HookTest from "../components/test.js";

storiesOf('HookTest', module)
	.add('basic process', () => {
		return {
			view: () => m(HookTest)
		};
	})

```

File: components/test.js

```javascript
import m from "mithril";

import {
    withHooks,
    useEffect,
    useState,
} from "mithril-hooks";

export default withHooks(function() {

    const [ count, set ] = useState(0);

    useEffect(() => {
        console.log(count);
        set(count + 1);
    }, []);

    return m('div', "hello");
});
```

In the result, you should have the `console.log(count);` showing `0` indefinitely in the console of the browser 😄 

I hope you'll figure it out better than me on your library.

Thx a lot for your work!

**Comment by ArthurClemens** [comment]
I've created a flems with most of the example code, but without Storybook itself:
[open flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiABOtWsWEA+FgHoOnKSAC+FdNlyICAKwRU6DJsTwQsAB1oji3ABLiA1gBV41sGKzdh+WYziSQgmiBBn7cAEIYcBDUAApi1PBw3PzcABQAlMlS3MCBgsQiMMQAriJoOXnW3JwQMADuiGmZ-FKB3O0dWKl2tE4u6ZXKgUNBaCHWAIJmZskV5dW1DU1ZbZ2pEVGx8YkDaCOBWPhYtMUMqatstNTFOAz4AI7FMCIAngDKMLDUxJbnIADEYgkwnSFFWUzMgXSlBotHM0GeeAARhgkZ8YXBPjBvhB6AgtABWRAANhUahAmBweF8xHwuhhBkYzC0slk3DQliwGCgvHMlmsdROUDY3DRiECrN5FisOW4dQgxEIPXscAo3GKmLexAwjDVGpgAFEwGBsdZlNw3HDPCAsArCCJoABaQgOODCYJ46zAOV25Wq9Wa7W6gOG42m7jmlK2xUOqB+vJoGAAD2l1jYMDAGGKUAFvtdqTApxx9Ayc3a424yG4dFOxDVmOIAGETgxuABdWb6rU6mCpAAM6QA3An2vqjSbvqlSy0yx0QrRYPgoLQAOapGsMIerdoN5u19ct6wAam4AEYt-NVJW2xfVoUSmVuF0AOQKZ9q5Dbp9-BTCNUAA0IT5l0aAASYAN2IZR-1BL8umEJFimIH4gkoWV6GoKBonsRpp2yXdDwPWtuBPc8r2tCY2DYEFVhvYc9gvDEsWLNB8RAAB2RBTwATjJdQqS0fBqDgPRYUMZkQBUNsqCwtAVSQVAKQ0PBo3taAAAEoB7PwYVKcgtBIYgzDgRBWVOMx7BXIS4VkVTY3UgAmfA+3wAAWWy7VjI4IDQOlROIF4zE0EA4GoB0zGMKhMS+YhcVYvA+0QBz2IAZgc3jVH44K7KdF1ejgTTtMikA9LwQzjNM2RzMs6ysA8mNctddSXNc-BT3kCA-HqtSoGdV0YQCoK8FC8LjGUaSlIEkBlW4GkVCAA)

This works as expected. Could it be that you are running multiple instances of Mithril?
